### ISSUE TITLE
Error when running on SpecFlow codebase

### ISSUE THREAD

**Issue by SabotageAndi** [alexmalimon/TestReporter.SpecFlow.Tool#1]
I tried your tool at the SpecFlow code base, but it throws an error:

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern)
   at TestReporter.SpecFlow.Tool.Helpers.Calls.StepDefinitionCallCountHelper.<>c__DisplayClass0_1.<CalculateNumberOfCalls>b__3(AttributeInformation x) in D:\Projects\TestReporter.SpecFlow.Tool\Helpers\Calls\StepDefinitionCallCountHelper.cs:line 17
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at TestReporter.SpecFlow.Tool.Helpers.Calls.StepDefinitionCallCountHelper.<>c__DisplayClass0_0.<CalculateNumberOfCalls>b__1(AttributeInformation baseStep) in D:\Projects\TestReporter.SpecFlow.Tool\Helpers\Calls\StepDefinitionCallCountHelper.cs:line 16
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at TestReporter.SpecFlow.Tool.Program.<>c.<Main>b__0_0(ConsoleArguments parsed) in D:\Projects\TestReporter.SpecFlow.Tool\Program.cs:line 83
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TestReporter.SpecFlow.Tool.Program.Main(String[] args) in D:\Projects\TestReporter.SpecFlow.Tool\Program.cs:line 135
```

**Comment by alexmalimon** [comment]
Hi @SabotageAndi,
Could you please provide steps to reproduce this issue?
P.S. Only thing I should notice is that '-p|--project' value should target to directory where (SpecFlow project) *.csproj file is located.
